tabItem(tabName = "boxplot",
        tabsetPanel( 
          tabPanel("Plots"),
          tabPanel("Data", 
             dataTableOutput('table__2_'),
             downloadButton('download__2_',"Download the data")),
          tabPanel("Plot Size", 
             numericInput("plotWidth__2_", "Plot Width (Required)", 1000),
             numericInput("plotHeight__2_", "Plot Height (Required)", NA)),
          tabPanel("Plot Title",
             textInput("title__2_", "Title 2", "Average hours per week"),
             numericInput("titleFont__2_", "Title Font", 10)), 
          tabPanel("Plot Legend",
             textInput("legendTitle__2_", "Legend Title", "Workclass"),
             numericInput("legendTitleSize__2_", "Legend Title Size", 10),
             numericInput("legendItemSize__2_", "Legend Item Size", 10),
             numericInput("legendKeySize__2_", "Legend Key Size", 5)), 
          tabPanel("Axis Labels",
             textInput("xLabel__2_", "x-Axis Label", "Races"),
             textInput("yLabel__2_", "y-Axis Label 1", "Average hours per week"),
             numericInput("textFont__2_", "textFont", 10)),
          tabPanel("Data Size", 
             numericInput("yDataMin__2_", "yData Minimum (Required)", 0),
             numericInput("yDataMax__2_", "yData Maximum (Required)", NA))),
        plotlyOutput("Boxplot__2_", height=800)
)
